### ISSUE TITLE
Wie Geht Der haha xD

### ISSUE THREAD

**Issue by Gtafgu** [LocutusV0nB0rg/GrieferBOT#1]

**Comment by LocutusV0nB0rg** [comment]
Hey, Hab die Nachricht jetzt erst gesehn, aber ich hab grade ein Update gemacht, kannst runterladen

**Comment by LocutusV0nB0rg** [comment]
Hab das Ticket mal geschlossen, haben uns ja jetzt getroffen gehabt

**Comment by LocutusV0nB0rg** [comment]
Ich habe noch ein INSTRUCTIONS.txt hinzugefügt, das informiert auch!
