### ISSUE TITLE
wenn 2 spieler in einer kassa sind das 1 automatisch gekickt wurd

### ISSUE THREAD

**Issue by Gtafgu** [LocutusV0nB0rg/GrieferBOT#14]

**Comment by LocutusV0nB0rg** [comment]
Das Problem bei dieser Idee ist, dass der BOt ja nicht wissen kann, wen er jetzt kicken soll... Soll er einen zufälligern Spieler dann kicken, oder wie stellst du dir das vor? Also no joke, was wäre dir am liebsten?

**Comment by Gtafgu** [comment]
Jo zufällig

**Comment by LocutusV0nB0rg** [comment]
Ich glaube das bekomme ich hin. Es ist aber in der TODO-Liste nicht ganz oben, einfach weil ich noch andere dringendere Dinge machen muss. Ich schließe das Ticket, sobald das entsprechende Update draussen ist.

**Comment by LocutusV0nB0rg** [comment]
Update ist mit 07_1 rausgekommen. Bitte ein Update machen, da dort auch der Crash mit den Boostern gefixt ist
