### ISSUE TITLE
wenn man eine fledermaus usw wurd sofort gekickt mit msg

### ISSUE THREAD

**Issue by Gtafgu** [LocutusV0nB0rg/GrieferBOT#15]

**Comment by LocutusV0nB0rg** [comment]
Warst du mehr als 3 Blöcke am Bot dran?, Wenn ja dann warst du in der "Kick-Aura", die hab ich eingeführt um Item-Steals einzudämmen.

Was meinst du mit Fledermaus? ^^

**Comment by Gtafgu** [comment]
Ah Oke Danke

**Comment by LocutusV0nB0rg** [comment]
Hat sich damit deine Frage erledigt, oder wolltest du auf einen bestimmten Bug aufmerksam machen den es ggf. gibt?

Ich schließe das Issue jetzt einfach mal, wenn ein Problem in die Richtugn auftaucht, dann informiere mich einfach in einem neuen Ticket
