### ISSUE TITLE
Letzte sache Bot automatisch laufen

### ISSUE THREAD

**Issue by Gtafgu** [LocutusV0nB0rg/GrieferBOT#16]

**Comment by LocutusV0nB0rg** [comment]
Meinst du dass der Bot im Hintergrund laufen soll während du mit einem anderen Account spielst? Das wird schwer werden, weil ich mich dazu erst in die Netzwerkkommunikation mit einem Minecraft-Server einlesen muss, und das ein sehr langfristiges Ticket sein wird.

Trotzdem nehme ich es natürlich zur Kenntnis und gebe dir hier auch Antwort, falls ich es geschafft haben sollte so etwas zu implementieren. Wenn das nicht ist was du meinst, bitte spezifiziere was du damit meinst, den Bot automatisch laufen zu lassen.
