### ISSUE TITLE
Zwei kammer trade 

### ISSUE THREAD

**Issue by saupiHd** [LocutusV0nB0rg/GrieferBOT#17]
Könntest du bald ein Update bringen mit welchen man mit zwei Kammern verkaufen kann? LG saupi

**Comment by LocutusV0nB0rg** [comment]
An dem Update bin ich grade dran ^^ Das wird der Split in Expert und Casual Version. Bitte benutze ausserdem das  Last Stable Release bis auf weiteres, da ich ein enormes Problem in meinem Code festgestellt habe und es möglich ist den Bot zu beklauen.!

**Comment by Gtafgu** [comment]
Jo Cool Danke!!

**Comment by saupiHd** [comment]
Ok gut und danach die Automatisierung? Des botes

**Comment by LocutusV0nB0rg** [comment]
Du meinst der vollständig-afk Modus, sodass man auch nen alt hinstellen kann? Danach kommt erstmal der Ankauf, das haben sich mehrere Leute gewünscht.

**Comment by LocutusV0nB0rg** [comment]
Und was danach komm hängt vorallem davon ab wieviel Zeit ich hab ^^

**Comment by ByteKrieger** [comment]
wie ist den der stand bist du noch dran an dem bot Locutusv0nb0rg?
