### ISSUE TITLE
das man evtl Stacksweise verkaufen kann also wenn meine beacons leer sind das die sich nachfüllen aus mein inv

### ISSUE THREAD

**Issue by Papadoubulus** [LocutusV0nB0rg/GrieferBOT#19]

**Comment by LocutusV0nB0rg** [comment]
Ich sehe den Punkt, das wird aber in Näherer Zukunft nicht Passieren. Was du bereits machen kannst, ist dass du 2Stack ins inv legst und Die Stacks im Bot mit Beacon1 und Beacon2 benennst. Den Preis setzt du auf einen Dollar Unterschied fest, und schreibt das auf die schilder, dass die Leute ggf. einen Dollar mehr zahlen müssen (weiß Gott, ist jetzt nich die Welt).

Wenn du wirklich ein ganzes Inventar an Items verkaufen willst, dass musss ich dir leider sagen, dass der Bot mit den Eigenschaften der Hotbar arbeitet, und so ein feature dann höchstens als Langzeitprojekt ins Auge gefasst werden kann.
