### ISSUE TITLE
Fehler 

### ISSUE THREAD

**Issue by SoNice1995** [LocutusV0nB0rg/GrieferBOT#20]
Ich benutze den bot leider macht er Fehler ich habe im 1. Slot beacon für 1100doller 
Im 2. Slot habe ich Haustier Marken für 800 doller und im 3. Slot habe ich eine spendenkarte für 1 doller 
Wenn jemand für 1 doller kauft bekommt er aber manchmal 1 beacon der aber 1100 doller kostet was kann Mann da machen ?

**Comment by LocutusV0nB0rg** [comment]
Schick mit mal bitte dein logfile.txt =)

**Comment by SoNice1995** [comment]
`Ich Bin Derzeitig, Als Verkaufs-Bot Auf /p h Afkfarm1qBin Grade Nur Als Verkaufs-Bot Online. /P h Afkfarm1qtestQIch Bin Afkqich bin afkqafkqqTest-BotqInitialisiere GrieferBOT | Bitte warten...Das sieht niemand... wenn doch, /msg LocutusV0nB0rg[+] Bestand zu Beginn des Durchlaufes{'Truhe': [[1, '1']]}{100: 'Truhe'}[+] Bereit für Kunden.[o] [2018-09-25 18:22] Spieler: bibicookiecore | Betrag: $100Dropped Truhe/msg bibicookiecore Danke für ihren Einkauf![Spieler | bibicookiecore -> mir] hi
/msg bibicookiecore Test-Bot[Spieler | bibicookiecore -> mir] hi
/msg bibicookiecore Test-BotBei Fehlern Bitte Mich In forum Kontaktieren! Unter KonservationqInitialisiere GrieferBOT | Bitte warten...Das sieht niemand... wenn doch, /msg LocutusV0nB0rg[+] Bestand zu Beginn des Durchlaufes{'Beacon': [[1, '1']], 'Haustier-Marke': [[1, '2']], 'Spende': [[1, '3']]}{1100: 'Beacon', 800: 'Haustier-Marke', 1: 'Spende'}[+] Bereit für Kunden.[o] [2018-09-25 20:23] Spieler: KiritoKirigaya | Betrag: $1Dropped Spende/msg KiritoKirigaya Danke für ihren Einkauf![o] [2018-09-25 20:35] Spieler: KiritoKirigaya | Betrag: $1/pay KiritoKirigaya 1.0/msg KiritoKirigaya Dieses Item ist leider ausverkauft. Hier hast du dein Money wieder![o] [2018-09-25 20:38] Spieler: KiritoKirigaya | Betrag: $1/pay KiritoKirigaya 1.0/msg KiritoKirigaya Dieses Item ist leider ausverkauft. Hier hast du dein Money wieder![Griefer | KiritoKirigaya -> mir] jo
/msg KiritoKirigaya Bei Fehlern Bitte Mich In forum Kontaktieren! Unter KonservationqInitialisiere GrieferBOT | Bitte warten...Das sieht niemand... wenn doch, /msg LocutusV0nB0rg[+] Bestand zu Beginn des Durchlaufes{'Beacon': [[10, '1']], 'Haustier-Marke': [[4, '2']], 'Spende': [[60, '3']]}{1100: 'Beacon', 800: 'Haustier-Marke', 1: 'Spende'}[+] Bereit für Kunden.[o] [2018-09-25 20:41] Spieler: KiritoKirigaya | Betrag: $1Dropped Spende/msg KiritoKirigaya Danke für ihren Einkauf![o] [2018-09-25 20:44] Spieler: KiritoKirigaya | Betrag: $1Dropped Spende/msg KiritoKirigaya Danke für ihren Einkauf![o] [2018-09-25 20:44] Spieler: KiritoKirigaya | Betrag: $1Dropped Spende/msg KiritoKirigaya Danke für ihren Einkauf![o] [2018-09-25 20:44] Spieler: KiritoKirigaya | Betrag: $1Dropped Spende/msg KiritoKirigaya Danke für ihren Einkauf![o] [2018-09-25 20:44] Spieler: KiritoKirigaya | Betrag: $1Dropped Spende/msg KiritoKirigaya Danke für ihren Einkauf![o] [2018-09-25 20:44] Spieler: KiritoKirigaya | Betrag: $1Dropped Spende/msg KiritoKirigaya Danke für ihren Einkauf![o] [2018-09-25 20:44] Spieler: KiritoKirigaya | Betrag: $1Dropped Spende/msg KiritoKirigaya Danke für ihren Einkauf![o] [2018-09-25 20:45] Spieler: KiritoKirigaya | Betrag: $1Dropped Spende/msg KiritoKirigaya Danke für ihren Einkauf![o] [2018-09-25 20:45] Spieler: KiritoKirigaya | Betrag: $1Dropped Spende/msg KiritoKirigaya Danke für ihren Einkauf![o] [2018-09-25 20:45] Spieler: KiritoKirigaya | Betrag: $1Dropped Spende/msg KiritoKirigaya Danke für ihren Einkauf![o] [2018-09-25 20:45] Spieler: KiritoKirigaya | Betrag: $1Dropped Spende/msg KiritoKirigaya Danke für ihren Einkauf![o] [2018-09-25 20:45] Spieler: KiritoKirigaya | Betrag: $1Dropped Spende/msg KiritoKirigaya Danke für ihren Einkauf![o] [2018-09-25 20:45] Spieler: KiritoKirigaya | Betrag: $1Dropped Spende/msg KiritoKirigaya Danke für ihren Einkauf![o] [2018-09-25 20:45] Spieler: KiritoKirigaya | Betrag: $1Dropped Spende/msg KiritoKirigaya Danke für ihren Einkauf![o] [2018-09-25 20:45] Spieler: KiritoKirigaya | Betrag: $1Dropped Spende/msg KiritoKirigaya Danke für ihren Einkauf![o] [2018-09-25 20:45] Spieler: KiritoKirigaya | Betrag: $1Dropped Spende/msg KiritoKirigaya Danke für ihren Einkauf![o] [2018-09-25 20:45] Spieler: KiritoKirigaya | Betrag: $1Dropped Spende/msg KiritoKirigaya Danke für ihren Einkauf![o] [2018-09-25 21:22] Spieler: SoNice1995 | Betrag: $1,100Dropped Beacon/msg SoNice1995 Danke für ihren Einkauf![o] [2018-09-25 21:23] Spieler: KiritoKirigaya | Betrag: $1,100Dropped Beacon/msg KiritoKirigaya Danke für ihren Einkauf![o] [2018-09-25 21:25] Spieler: KiritoKirigaya | Betrag: $1Dropped Spende/msg KiritoKirigaya Danke für ihren Einkauf![o] [2018-09-25 21:25] Spieler: KiritoKirigaya | Betrag: $1Dropped Spende/msg KiritoKirigaya Danke für ihren Einkauf![o] [2018-09-25 21:25] Spieler: KiritoKirigaya | Betrag: $1Dropped Spende/msg KiritoKirigaya Danke für ihren Einkauf![o] [2018-09-25 21:30] Spieler: noswift | Betrag: $1Dropped Spende/msg noswift Danke für ihren Einkauf![o] [2018-09-25 21:31] Spieler: KiritoKirigaya | Betrag: $1Dropped Spende/msg KiritoKirigaya Danke für ihren Einkauf![o] [2018-09-25 21:33] Spieler: KiritoKirigaya | Betrag: $1Dropped Spende/msg KiritoKirigaya Danke für ihren Einkauf![o] [2018-09-25 21:56] Spieler: Steinheit | Betrag: $1,100Dropped Beacon/msg Steinheit Danke für ihren Einkauf![o] [2018-09-25 21:59] Spieler: KiritoKirigaya | Betrag: $1Dropped Spende/msg KiritoKirigaya Danke für ihren Einkauf![o] [2018-09-25 22:02] Spieler: KiritoKirigaya | Betrag: $1Dropped Spende/msg KiritoKirigaya Danke für ihren Einkauf![o] [2018-09-25 22:02] Spieler: KiritoKirigaya | Betrag: $1,100Dropped Beacon/msg KiritoKirigaya Danke für ihren Einkauf![o] [2018-09-25 22:06] Spieler: BIGLUKASO | Betrag: $1Dropped Beacon/msg BIGLUKASO Danke für ihren Einkauf![o] [2018-09-25 22:09] Spieler: KiritoKirigaya | Betrag: $1,100Dropped Beacon/msg KiritoKirigaya Danke für ihren Einkauf![o] [2018-09-25 22:12] Spieler: Steinheit | Betrag: $1,100Dropped Beacon/msg Steinheit Danke für ihren Einkauf![o] [2018-09-25 22:14] Spieler: KiritoKirigaya | Betrag: $1Dropped Beacon/msg KiritoKirigaya Danke für ihren Einkauf!`

**Comment by SoNice1995** [comment]
Ja bin mir sicher das die reihenfolge stimmt weil es hat ja bei einigen einkäufen funktioniert

**Comment by LocutusV0nB0rg** [comment]
Kannst du das bitte als Textdatei hochladen und mir den Link schicken xD 

Mit dem kann ich leider nicht arbeiten :P

**Comment by SoNice1995** [comment]
https://www.file-upload.net/download-13328982/logfile.txt.html

**Comment by SoNice1995** [comment]
Der Fehler gefunden Wenn minecraft laggt dann passiert das der Fehler liegt Client seitig und nicht Software bedingt 
Wichtig minecraft mit hoher Priorität starten und mehr RAM zuweisen dann passiert das nicht mehr
