### ISSUE TITLE
Automatischer Kick nach bestimmter Zeit, Ankauf

### ISSUE THREAD

**Issue by agentcru** [LocutusV0nB0rg/GrieferBOT#22]
Hey könntest du einbauen dass Leute nach einer bestimmten Zeit, die sie ohne etwas zu tuen in der Kammer stehen, gekickt werden und, dass der Bot auch Items ankaufen kann?

**Comment by LocutusV0nB0rg** [comment]
Ankauf ist in Arbeit ud komplizierter als gedacht. Die afk-Leute kann ich prüfen, da muss ich aber noch die Details ausarbeiten!
