### ISSUE TITLE
Bot stürzt ab/ beendet das programm

### ISSUE THREAD

**Issue by MrB3N0** [LocutusV0nB0rg/GrieferBOT#23]
Der Bot beendet sich einfach nach ca. 10-15min. und zeigt dann solche Sachen im Log an:

/msg MrB3N Hi ich bin der Bot von MrB3N (bitte Schilder lesen)
[o] [2018-10-24 06:26] Spieler: tIRIUS2K | Betrag: die
Bot von MrB3N (Bitte Schilder lesen)
Initialisiere GrieferBOT | Bitte warten...

Das sieht niemand... wenn doch, /msg LocutusV0nB0rg

[+] Bestand zu Beginn des Durchlaufes
{'Redstone': [[9, '1']], 'Gold': [[4, '2']], 'Eisen': [[5, '3']], 'Wolle': [[56, '4']], 'Seelaterne': [[64, '5']], 'Prismarin': [[63, '6']]}
{15: 'Redstone', 21: 'Gold', 20: 'Eisen', 1: 'Wolle', 5: 'Seelaterne', 3: 'Prismarin'}
[+] Bereit für Kunden.
[o] [2018-10-24 06:41] Spieler: Nemesis091 | Betrag: Premium**                      (-- hier

ist das nur bei mir so?

lg. Ben

**Comment by ByteKrieger** [comment]
könnte es sein das er abstürzt wenn ein booster aktiviert wird diese Problem hab ich momentan extremst

**Comment by ByteKrieger** [comment]
schade das der Entwickler nicht mehr aktiv zu sein scheint

**Comment by LocutusV0nB0rg** [comment]
Liegt an den Boostern, Mach ein update auf 06, dann ist alles gut (hoffe ich) ;)

Pls verzeih die Inaktivität
