### ISSUE TITLE
Bot crashed wegen neuer funktionen  auf gg

### ISSUE THREAD

**Issue by ByteKrieger** [LocutusV0nB0rg/GrieferBOT#24]
der bot crasht durch den neuen status von supremes und durch aktivieren oder deaktivieren von boostern die jeder spieler für den gesamten server aktivieren kann

**Comment by ByteKrieger** [comment]
wer ein fix hat würde mich sehr freuen!

**Comment by ByteKrieger** [comment]
Muss mich korrigieren nur durch aktivieren des boosters

**Comment by MrB3N0** [comment]
Lade dir einfach 1.8 Labymod herunter und mache einen Chatfilter mit den cotains Booster rein.

**Comment by LocutusV0nB0rg** [comment]
Ich habe einen Fix veröffentlicht! GrieferBOT06

**Comment by ByteKrieger** [comment]
nice thx

**Comment by ByteKrieger** [comment]
du bist der beste
