### ISSUE TITLE
Hallo ;)

### ISSUE THREAD

**Issue by QuinnXT** [LocutusV0nB0rg/GrieferBOT#25]
Wie startet man denn den bot Brauch man noch ein Zusatz Programm.
Oder geht das alles nur über die exe die im Download Enthalten ist?

**Comment by MrB3N0** [comment]
Es geht über die normale exe Datei. Hättest es auch einfach Mal ausprobieren können.
LG MrB3N (Ben)

**Comment by QuinnXT** [comment]
Danke dann muss ich es an nem anderen PC Mal probieren
Weil weiter als die Preiseingabe ging es bei mir nicht. Daher hab ich gefragt gehabt

**Comment by MrB3N0** [comment]
Drückst du auch nachdem du alles eingegeben hast 2 Mal enter?

**Comment by MrB3N0** [comment]
Aber?

**Comment by MrB3N0** [comment]
Hat er Windows 10?

**Comment by QuinnXT** [comment]
Ne das ist ein alter Rechner mit Win7 64

Heute Versuche ich es Mal an win10 64

**Comment by MrB3N0** [comment]
Also Win8 geht nicht

**Comment by MrB3N0** [comment]
Da fehlt eine system datei

**Comment by LocutusV0nB0rg** [comment]
Windows 10 ist notwendig, und zwar auf 64 bit. Alles andere geht nicht.
