### ISSUE TITLE
eventl fehler

### ISSUE THREAD

**Issue by ByteKrieger** [LocutusV0nB0rg/GrieferBOT#26]
Problem ist folgendes bei namen mit w Wird bei mir das Fenster minimiert oder maximiert und der Chat geöffnet es bleibt dann auch so weiß nicht ob das ein Fehler bei mir ist oder beim bot.

Des weiteren ist mit der neuen Version 7.01 das Problem bei mir dass es einen Spam Kick ausgelöst dadurch dass es dreimal hintereinander schnell /near macht vielleicht  bei aktiviertem slow Chat?

**Comment by LocutusV0nB0rg** [comment]
Japp, das kann sein. Ich arbeite bereits an der 08, die bringt einen Fix dafür =)

**Comment by ByteKrieger** [comment]
Bin erstmal bei der 6 er geblieben werd mir die 8er dann anschauen wenn sie raus ist xD

**Comment by ByteKrieger** [comment]
Muss den bug mit w nochmals ansprechen hatte ein großes Problem damit

**Comment by ByteKrieger** [comment]
Bitte dringend fixen
