### ISSUE TITLE
Automatisch Werbung machen

### ISSUE THREAD

**Issue by Altpapier** [LocutusV0nB0rg/GrieferBOT#27]
Hey,
ich fände es noch richtig nice, wenn der Bot alle 20 Sekunden oder so in den Chat eine Nachricht, die man vorher in den Bot eingibt in den Chat schreibt. Und wenn er diese gesendet hat, nach 10 Sekunden ein . in den Chat schreibt und dann wieder in 10 Sekunden die Nachricht.

Dann fände ich den Bot perfekt!

**Comment by LocutusV0nB0rg** [comment]
Ich persönlich bin gegen Spam, daher wede ich keine solche Funktion einprogrammieren. Wenn ihr Spam für notwendig erachtet, macht es mit einem Client, der euch eine Spammer-Funktion bietet.

**Comment by Altpapier** [comment]
Welchen gibt es denn? Kenn keinen

**Comment by ByteKrieger** [comment]
Altpapier Wurst Client zb dir sollte aber klar sein das die meisten Funktionen davon auf gg verboten sind also überlege dir gut was du davon benutzt
