### ISSUE TITLE
Abge schenkungen

### ISSUE THREAD

**Issue by ByteKrieger** [LocutusV0nB0rg/GrieferBOT#28]
Wäre nett nen Filter hinzuzufügen wenn Abge payt das das Geld nicht zurück geschickt wird. Bzw. dazu ne kleine Funktion mit rein.  Mit Rückantwort danke für die Spende oder so.

Weil seien wir mal ehrlich mit seinem Mainacc kauft der bestimmt ned bei nem Bot ein. 
Bzw gibts es dazu schon Überlegungen?

**Comment by ByteKrieger** [comment]
Gestern hat er zb 15k verteilt zum Glück hatte ich bot da ned an. Da ist mir das eingefallen xD

**Comment by Altpapier** [comment]
Was ist bei dir passiert MRB3N?

**Comment by ByteKrieger** [comment]
Wäre cool wenn das ausgeschlossen wird

**Comment by LocutusV0nB0rg** [comment]
Der Bot ist als Verkaufsbot gedacht, nicht als Spendensammelstation... Tut mir leid, dsa werde ich glaube ich nicht umsetzen
