### ISSUE TITLE
kick durch /near Spam

### ISSUE THREAD

**Issue by Altpapier** [LocutusV0nB0rg/GrieferBOT#29]
Problem: Der Bot Spammt ja nacheinander /near. Aber manchmal tut er es so oft, dass ich von GrieferGames für "Bitte unterlasse das Spammen von Commands" gekickt werde. VG Altpapier

**Comment by ByteKrieger** [comment]
Jap ist dem dev bekannt siehe Post von mir

**Comment by Altpapier** [comment]
Oh ups sry
