### ISSUE TITLE
INSTRUCTIONS.txt 

### ISSUE THREAD

**Issue by BlueGaming** [LocutusV0nB0rg/GrieferBOT#3]
Ich finde irgendwie nicht diese INSTRUCTIONS.txt und die REQUIREMENTS.txt bin ich blind D:

**Comment by LocutusV0nB0rg** [comment]
Nein du bist nicht Blind, ich hab die noch nicht geschrieben, danke Für deine Meldung, kommt ganz oben aufs TODO

**Comment by LocutusV0nB0rg** [comment]
Ich hab die entsprechenden Dateien hinzugefügt! Ticket geschlossen, Vielen DAnk für deine Rückmeldung =)
