### ISSUE TITLE
Automatsches Werbung schreiben

### ISSUE THREAD

**Issue by finn1476** [LocutusV0nB0rg/GrieferBOT#30]
Wäre es möglich das der bot Automatisch Werbung schreibt könnte man so etwas einfügen?

**Comment by agentcru** [comment]
Dazu kann ich dir auch ne Mod einstellen und aufsetzen. Die Mod ist auch komplett mit dem Bot kompatibel

**Comment by finn1476** [comment]
Könntest du mir die evtl geben?

**Comment by agentcru** [comment]
Mache ich nachher

**Comment by finn1476** [comment]
Ok danke im voraus

**Comment by LocutusV0nB0rg** [comment]
Das mit den Spam hatten wir schon... Ich unterstütze Spam nicht, daher keine solche Funktion =)

agentcru hat da gegebenenfalls nen Vorschlag
