### ISSUE TITLE
Ich habe ein Problem

### ISSUE THREAD

**Issue by finn1476** [LocutusV0nB0rg/GrieferBOT#31]
Ist es Normal das der Bot immer nur 1 Item VErkauft und dann sagt Item ausverkauft Hier hast du dein Monney wieder ich habe immer im inv 10 Becone und 17 Karten Zu anfang zeigt er mir immer an
Zitiere:[+] Bestand zu Beginn des Durchlaufes

{'Leuchtfeuer': [[1, '1']], 'Karte 1': [[1, '2']], 'Karte 2': [[1, '3']], 'Karte 3': [[1, '4']], 'Karte 4': [[1, '5']], 'Karte 5': [[1, '6']]}

{950: 'Leuchtfeuer', 199: 'Karte 1', 198: 'Karte 2', 197: 'Karte 3', 196: 'Karte 4', 195: 'Karte 5'}

[+] Bereit für Kunden.

Kann mir da wer helfen´? Für mich sieht das so aus als ob er immer nur 1 Item erkennt weil überall ne 1 steht Ich verwende Sellingbot 6
System:Win 10 Home 64 Bit

**Comment by ByteKrieger** [comment]
ist kein bug du musst die nzahl genau mitangeben lies es genau wenn du die exe startest lg bytekrieger

**Comment by MrB3N0** [comment]
Du musst die Zahl bei Wie viele Items sollen verkauft werden auf z.b 10 stellen wenn du möchtest das 10 Items verkauft werden.

LG MrB3N (Ben)

**Comment by finn1476** [comment]
Oh danke
