### ISSUE TITLE
Kompilieren

### ISSUE THREAD

**Issue by agentcru** [LocutusV0nB0rg/GrieferBOT#32]
Hey wie kann ich die bearbeitete Datei kompilieren habe da ein paar Probleme

**Comment by ByteKrieger** [comment]
Wäre ne Idee ne readme  dazu zu machen

**Comment by LocutusV0nB0rg** [comment]
Kompilieren kannst du es wie du willst, es gibt verschiedene Wege dazu, ich benutze pyinstaller, es gibt aber auch andere Wege. Wie du das kompilieren willst, musst du esntscheiden, solange du den Code hast ist es egal WIE du ihn in eine exe verpackst

**Comment by agentcru** [comment]
ok könntest du da vllt ne readme oder so dazu machen wie das genau geht

**Comment by agentcru** [comment]
Habe nen Fehler beim kompilieren:
  File ".\SellingBot07_1.py", line 30, in <module>
    from pynput.keyboard import Key, Controller, KeyCode
ModuleNotFoundError: No module named 'pynput'

**Comment by LocutusV0nB0rg** [comment]
Das ist ein zusätzliches Modul dass du erst installieren musst. Bitte informiere dich über pip und wie man Module installiert

**Comment by agentcru** [comment]
Ok habs schon geschafft
