### ISSUE TITLE
In Kontakt treten

### ISSUE THREAD

**Issue by 1static** [LocutusV0nB0rg/GrieferBOT#33]
Hey ich würde gerne mal mit dir in Kontakt treten, da es um ein angebot geht. Währe das möglich? wenn ja wann?

**Comment by 1static** [comment]
*wenn ja wie?

**Comment by LocutusV0nB0rg** [comment]
Bitte spezifizieren, außerdem sehe ich keinen Grund, warum du mir das Angebot nicht hier schreiben könntest, wenn du schon ein unnötiges Ticket erstellst, kann man es ja wenigstens sinnvoll Nutzen ^^

**Comment by 1static** [comment]
will nd das alle mitlesen xd

**Comment by 1static** [comment]
iwas ts oder so?

**Comment by LocutusV0nB0rg** [comment]
Îch komme
