### ISSUE TITLE
Wie funktioniert das System?

### ISSUE THREAD

**Issue by Justin2211** [LocutusV0nB0rg/GrieferBOT#35]
Hallo

Ich habe den gedownloadeten Ordner entpackt und habe die Exe gestartet mal nehme ich die Neuste manchmal die Stable immer am ausprobieren.

Jetzt gebe ich die Items ein die Verkauft werden sollen und lege die auf die Slots, dann drücke ich einfach enter und der springt in die nächste Zeile und es passiert nichts, dann gehe ich in Minecraft und gebe irgendwas in den Chat ein und drücke Enter, dann schreibt der austomatisch in den Minecraft Chat das der Bot initialisiert wird und er bereit für kunden ist.

Aber wenn jetzt ein Spieler kommt und ihm Geld payt dann droppt er nichts sondern nur ein True kommt in der CMD.

Muss ich dem Bot eine Msg schreiben oder wie funktioniert er?

Mit Freundlichen Grüßen

**Comment by LocutusV0nB0rg** [comment]
Hmm das ist merkwürdig...

ICh guck mir das mal an. Schick bitte dein Logfile zu überprüfung hier rein =)
